from __future__ import annotations

from typing import Protocol

from app.workshop.domain.entities import WorkshopSession


class WorkshopRepositoryPort(Protocol):
    def save(self, session: WorkshopSession) -> WorkshopSession: ...
    def get_by_id(self, workshop_id: str) -> WorkshopSession | None: ...
    def get_by_chat_session(self, chat_session_id: str) -> WorkshopSession | None: ...
    def list_recent(self, limit: int = 20) -> list[WorkshopSession]: ...
    def delete(self, workshop_id: str) -> bool: ...
