from __future__ import annotations

from typing import Protocol

from app.knowledge.domain import KnowledgeEntry
from app.knowledge.domain import Identity


class KnowledgeRepositoryPort(Protocol):
    def save(self, entry: KnowledgeEntry) -> KnowledgeEntry: ...

    def list_all(self) -> list[KnowledgeEntry]: ...

    def list_recent(self, limit: int = 20) -> list[KnowledgeEntry]: ...

    def list_by_engram(self, engram_id: str) -> list[KnowledgeEntry]: ...

    def count(self) -> int: ...


class EngramRepositoryPort(Protocol):
    def save(self, identity: Identity) -> Identity: ...

    def get_by_id(self, engram_id: str) -> Identity | None: ...

    def list_all(self) -> list[Identity]: ...

    def list_recent(self, limit: int = 20) -> list[Identity]: ...

    def delete(self, engram_id: str) -> bool: ...

    def count(self) -> int: ...